In [4]:
import os
import numpy as np
import pandas as pd
import yfinance as yf

In [5]:
import pandas as pd
df = pd.read_csv('D:/ind_nifty500list.csv', sep=',', header=0, na_values=[''], quotechar='"')
df

,Company Name,Industry,Symbol,Series,ISIN Code
0,360 ONE WAM Ltd.,Financial Services,360ONE,EQ,INE466L01038
1,3M India Ltd.,Diversified,3MINDIA,EQ,INE470A01017
2,ABB India Ltd.,Capital Goods,ABB,EQ,INE117A01022
3,ACC Ltd.,Construction Materials,ACC,EQ,INE012A01025
4,ACME Solar Holdings Ltd.,Power,ACMESOLAR,EQ,INE622W01025
...,...,...,...,...,...
495,Zen Technologies Ltd.,Capital Goods,ZENTEC,EQ,INE251B01027
496,Zensar Technolgies Ltd.,Information Technology,ZENSARTECH,EQ,INE520A01027
497,Zydus Lifesciences Ltd.,Healthcare,ZYDUSLIFE,EQ,INE010B01027
498,Zydus Wellness Ltd.,Fast Moving Consumer Goods,ZYDUSWELL,EQ,INE768C01028
499,eClerx Services Ltd.,Services,ECLERX,EQ,INE738I01010

In [6]:
df.columns = (((df.columns
              .str.strip()
              .str.lower())
              .str.replace(" ","_")).str.replace("-","_").
              str.replace("/","_"))

In [7]:
df.drop(columns=['isin_code','company_name','series'],inplace=True)

In [8]:
df.rename(columns={'industry':'sector'},inplace=True)

In [9]:
df['yf_ticker'] = df['symbol'] + '.NS'

In [10]:
valid = []
invalid = []
for ticker in df['yf_ticker']:
    data = yf.download(ticker,period='5d',progress=False)

    if data.empty:
        invalid.append(ticker)

    else:
        valid.append(ticker)

print("Valid:", len(valid))
print("Invalid:", len(invalid))
print(invalid)

Valid: 500
Invalid: 0
[]

In [13]:
df.to_csv(
    r"C:\Users\Ak\PycharmProjects\POR Dashboard\data\raw\nifty500_universe.csv",
    index=False
)

In [14]:
pd.read_csv(
    r"C:\Users\Ak\PycharmProjects\POR Dashboard\data\raw\nifty500_universe.csv"
).head()

                   sector     symbol     yf_ticker
0      Financial Services     360ONE     360ONE.NS
1             Diversified    3MINDIA    3MINDIA.NS
2           Capital Goods        ABB        ABB.NS
3  Construction Materials        ACC        ACC.NS
4                   Power  ACMESOLAR  ACMESOLAR.NS

In [15]:
os.getcwd()

'C:\\Users\\Ak\\PycharmProjects\\POR Dashboard\\notebooks'

In [21]:
ticker = df['yf_ticker'].iloc[0]

data = yf.download(
    ticker,
    period="5y",
    auto_adjust=False,
    progress=False,multi_level_index=False
)

data.head()

             Adj Close       Close    High         Low      Open  Volume
Date
2021-08-31  363.402130  405.487488  407.50  390.262512  392.2500  397344
2021-09-01  358.663422  400.200012  415.00  395.000000  409.9375  206156
2021-09-02  358.719452  400.262512  412.50  395.512512  407.5000  146008
2021-09-03  354.328033  395.362488  401.25  390.262512  400.5000  115372
2021-09-06  359.234802  400.837494  404.75  395.500000  396.2500  523692

In [20]:
data.head()
data.shape
data.columns

AttributeError: 'Series' object has no attribute 'columns'